DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'role') THEN
        CREATE TYPE role AS
            ENUM ('admin', 'user');
    END IF;
END$$;


CREATE TABLE IF NOT EXISTS users (
    id          integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    userName    varchar(100) UNIQUE CHECK (userName <> ''),
    email       varchar(240) UNIQUE check (email <> ''),
    authority   role NOT NULL
);


INSERT into users (userName, email, authority)
VALUES ('David Pace', 'ldavidpace@gmail.com', 'admin'),
    ('Alycia Pace', 'alyciapaceart@gmail.com', 'admin');
