

CREATE TABLE IF NOT EXISTS quiz (
    id          integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name        varchar(100) UNIQUE CHECK (name <> '')
);

CREATE TABLE IF NOT EXISTS questions (
    id          integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    quiz_id     integer NOT NULL REFERENCES quiz (id),
    question    varchar(2000) NOT NULL
);

CREATE TABLE IF NOT EXISTS answers (
    id          integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    question_id integer NOT NULL REFERENCES questions (id),
    answers     varchar(2000) NOT NULL
);
